# Site settings
meta_description: 杨睿龙;个人博客;生命不止;折腾不休
name: 乱写
description: Nothing here, right?
email: yangrlx@gmail.com
author: yrl
url: http://localhost:4000
resume_site: http://localhost/Resume.io/
github: https://github.com/abomb4/
baseurl: ""
motto: It's our wits that make us men.
banner: 与其感慨路难行，不如马上出发。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: abomb4
# highlighter: Pygments
highlighter: rouge

# serve
host: 0.0.0.0

# Build settings
markdown: kramdown

baidu_analysis: 994cc0d0415ea6761ae9:w

FB:
  comments :
    provider : 000
    duoshuo:
        short_name : 000
    disqus :
        short_name : 000
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
