# Site metadata
meta_description: 个人博客
name: 一名 CURD 码农的成长之路
description: 个人博客
email: yangrlx@gmail.com
author: yrl
url: http://localhost:4000
resume_site: http://localhost/Resume.io/
github: https://github.com/abomb4/
baseurl: ""
motto: It's our wits that make us men.
banner: 与其感慨路难行，不如马上出发。

# Functional configurations
#permalink: /:categories/:year/:month/:day/:title/
plugins: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
paginate: 10
excerpt_separator: <!--more-->

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: abomb4
# highlighter: Pygments
highlighter: rouge

# serve
host: 0.0.0.0

# Build settings
markdown: kramdown
